app = "standupcrossfit"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = "--migrate"

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:8080"
ASPNETCORE_FORWARDEDHEADERS_ENABLED = "true"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
